-- Table 1
DROP TABLE IF EXISTS table1;
CREATE TABLE table1 (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50),
    age INT
);

INSERT INTO table1 (name, age)
SELECT 
    CONCAT('Name', FLOOR(RAND() * 1000)) AS name,
    FLOOR(RAND() * 100) AS age
FROM
    (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) AS t;

-- Table 2
DROP TABLE IF EXISTS table2;
CREATE TABLE table2 (
    id INT PRIMARY KEY AUTO_INCREMENT,
    address VARCHAR(100),
    city VARCHAR(50)
);

INSERT INTO table2 (address, city)
SELECT 
    CONCAT('Address', FLOOR(RAND() * 1000)) AS address,
    CONCAT('City', FLOOR(RAND() * 1000)) AS city
FROM
    (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) AS t;
